version: 2
sources:
    - name: datafeed_shared_schema
      database: "{{('dbt_db')}}"
      schema: staging_layer
      tables:
        - name: stg_customer_data
        - name: stg_payments_data
        - name: stg_order_data
        - name: STG_ITEMS_DATA
        - name: STG_PRODUCT_DATA
        - name: STG_SUPPLIES_DATA
