version: 2
sources:
    - name: datafeed_shared_schema
      database: "{{('dbt_db')}}"
      schema: staging_layer
      tables:
        - name: stg_customer_data
        - name: stg_payments_data
        - name: stg_order_data
        - name: stg_stores_data
        - name: stg_products_data
        - name: stg_supplies_data
        - name: stg_items_data
        - name: emp